#!/usr/bin/env sh

# window
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          autoraise
yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 on
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                resize
yabai -m config mouse_action2                move
yabai -m mouse_drop_action stack
## opacity
yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.8
## border
yabai -m config window_border                on
yabai -m config window_border_width          1
yabai -m config active_window_border_color   0xffbfff00 # limelight
yabai -m config normal_window_border_color   0x00bfff00
yabai -m config insert_feedback_color        0xaad75f5f
## shadow
yabai -m config window_shadow                off

# layout
# mission-control desktop labels
yabai -m space 1  --label code
yabai -m space 2  --label shell
yabai -m space 3  --label browser
yabai -m space 4  --label note
yabai -m space 5  --label file
yabai -m space 6  --label message
yabai -m space 7  --label client

yabai -m config layout                       bsp
yabai -m config top_padding                  0
yabai -m config bottom_padding               0
yabai -m config left_padding                 0
yabai -m config right_padding                0
yabai -m config window_gap                   0
yabai -m config external_bar                 off:45:0
yabai -m config --space code layout          stack
yabai -m config --space browser layout       stack


# rules
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^uTools$"             manage=off
yabai -m rule --add app="^PyCharm$"                       border=off space=code 
yabai -m rule --add app="^Visual Studio Code$"            border=off space=code
yabai -m rule --add app="^iTerm$"                                    space=shell
yabai -m rule --add app="^Google Chrome$"                 border=off space=browser
yabai -m rule --add app="^Safari$"                                   space=browser
yabai -m rule --add app="^Notes$"                                    space=note
yabai -m rule --add app="^Logseq$"                                   space=note
yabai -m rule --add app="^Joplin$"                                   space=note
yabai -m rule --add app="^Finder$"                                   space=file
yabai -m rule --add app="^Marta$"                                    space=file
yabai -m rule --add app="^WeChat$"                                   space=message
yabai -m rule --add app="^Studio 3T$"                                space=client
