#!/usr/bin/env sh

# window
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 on
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                resize
yabai -m config mouse_action2                move
yabai -m mouse_drop_action stack
## opacity
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.8
## border (Window borders (and all related options/properties) have been removed)
# yabai -m config window_border                off
# yabai -m config window_border_width          1
# yabai -m config active_window_border_color   0xffbfff00 # limelight
# yabai -m config normal_window_border_color   0x00bfff00
# yabai -m config insert_feedback_color        0xaad75f5f
## shadow
yabai -m config window_shadow                off


# display
## please refer to the `display` section of `skhdrc`. 
## When switching displays, `mouse_follows_focus` will temporarily be enabled, allowing the mouse to follow to another display.
yabai -m signal --add event=display_changed action="yabai -m config mouse_follows_focus off"


# layout
# mission-control desktop labels
yabai -m space 1   --label s1
yabai -m space 2   --label s2
yabai -m space 3   --label s3
yabai -m space 4   --label s4
yabai -m space 5   --label s5
yabai -m space 6   --label s6
yabai -m space 7   --label s7
yabai -m space 8   --label s8
yabai -m space 9   --label s9
yabai -m space 10  --label s0

yabai -m config layout                       float
yabai -m config top_padding                  0
yabai -m config bottom_padding               0
yabai -m config left_padding                 0
yabai -m config right_padding                0
yabai -m config window_gap                   0
yabai -m config external_bar                 off:26:0
yabai -m config --space s1 layout            bsp
yabai -m config --space s2 layout            bsp
yabai -m config --space s3 layout            stack    window_gap 50 top_padding 100 right_padding 100 bottom_padding 100 left_padding 100
yabai -m config --space s4 layout            stack    window_gap 50 top_padding 100 right_padding 100 bottom_padding 100 left_padding 100
yabai -m config --space s5 layout            bsp
yabai -m config --space s6 layout            bsp
yabai -m config --space s7 layout            stack
yabai -m config --space s8 layout            bsp
yabai -m config --space s9 layout            stack    window_gap 50 top_padding 100 right_padding 100 bottom_padding 100 left_padding 100
yabai -m config --space s0 layout            stack    window_gap 50 top_padding 100 right_padding 100 bottom_padding 100 left_padding 100


# rules (space=^<SPACE_SEL> requires SIP disabled to follow focus)
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^uTools$"             manage=off
yabai -m rule --add app="^Raycast$"            manage=off
yabai -m rule --add app="^iTerm$"                          space="^s1"
yabai -m rule --add app="^kitty$"                          space="^s1"
yabai -m rule --add app="^WezTerm$"                        space="^s2"
yabai -m rule --add app="^Alacritty$"                      space="^s2"
yabai -m rule --add app="^PyCharm$"                        space="^s3"
yabai -m rule --add app="^Visual Studio Code$"             space="^s3"
yabai -m rule --add app="^Zed$"                            space="^s3"
yabai -m rule --add app="^Notes$"                          space="^s3"
yabai -m rule --add app="^Logseq$"                         space="^s3"
yabai -m rule --add app="^Joplin$"                         space="^s3"
yabai -m rule --add app="^WeChat$"                         space="^s3"
yabai -m rule --add app="^VMware Fusion$"                  space="^s6"
yabai -m rule --add app="^Google Chrome$"                  space="^s7"
yabai -m rule --add app="^Safari$"                         space="^s7"


# border (by JankyBorders)
#/opt/homebrew/bin/borders active_color=0xff50fa7a inactive_color=0x0050fa7a width=3.0 style=square hidpi=on whitelist="alacritty" &
