#!/usr/bin/env bash

# git commit browser (enter for show, ctrl-d for diff, ` toggles sort)
# https://github.com/junegunn/dotfiles/blob/c6959cd4f/bashrc#L285
fzf-log() {
  local out shas sha q k
  while out=$(
    git log --graph --color=always --format="%C(auto)%h%d %s %C(black)%C(bold)- %an %cr" "$@" |
    fzf --ansi --multi --no-sort --reverse --query="$q" --tiebreak=index --print-query --expect=ctrl-d --toggle-sort=\`
  ); do
    q=$(head -1 <<< "$out")
    k=$(head -2 <<< "$out" | tail -1)
    shas=$(sed '1,2d;s/^[^a-z0-9]*//;/^$/d' <<< "$out" | awk '{print $1}')
    [ -z "$shas" ] && continue
    if [ "$k" = 'ctrl-d' ]; then
      git diff --color=always $shas
    else
      for sha in $shas; do
        git show --color=always $sha
      done
    fi
  done
}
